"""Configuration constants for ARC cohort scaffolding."""

from .buckets import AGE_BUCKETS, CAREER_YEAR_NOTES
from .positions import CORE_POSITIONS, SUPPORTED_POSITIONS
from .thresholds import (
    ELITE_SEASON_FINISH_CUTOFFS,
    STARTER_SEASON_FINISH_CUTOFFS,
    WEEKLY_DUD_FINISH_THRESHOLDS,
    WEEKLY_SPIKE_FINISH_THRESHOLDS,
)

__all__ = [
    "SUPPORTED_POSITIONS",
    "CORE_POSITIONS",
    "AGE_BUCKETS",
    "CAREER_YEAR_NOTES",
    "WEEKLY_SPIKE_FINISH_THRESHOLDS",
    "WEEKLY_DUD_FINISH_THRESHOLDS",
    "ELITE_SEASON_FINISH_CUTOFFS",
    "STARTER_SEASON_FINISH_CUTOFFS",
]
